### ISSUE TITLE
Start and Sign Up Page

### ISSUE THREAD

**Issue by Nitya-Pasrija** [Nitya-Pasrija/CB-DonationApp#12]
Slide 1 
![image](https://user-images.githubusercontent.com/97171261/185966334-53feab69-3a93-44a8-bd22-7a1e67166305.png)

Slide 2
![image](https://user-images.githubusercontent.com/97171261/185966300-1df3919c-3013-49f7-be85-60efa9edf945.png)

**Comment by Nikhila-KS** [comment]
hey
